### ISSUE TITLE
Cosm table broken on Chrome

### ISSUE THREAD

**Issue by DGHunter** [torg-codex/issues#10]
**URL:** /cosms/waldeck
**Reference Book:** Core Rules
**Page:** 72
~~~
description of the problem

The only usable cosms (ones that can be clicked on are Tombspace, Ukhann and Waldeck. The default result seems to be Waldeck

**Comment by manuel-hegner** [comment]
Tests showed that this is a problem with chrome, but not firefox. Will investigate further.

**Comment by manuel-hegner** [comment]
Should now be fixed

**Comment by DGHunter** [comment]
Excellent, thank you very much!
