### ISSUE TITLE
Codex claims I only have 4 Torg Eternity sourcebooks

### ISSUE THREAD

**Issue by nikgervae** [torg-codex/issues#61]
**URL:** https://torg-codex.com/
**Reference Book:** most
**Page:** not applicable
~~~
When I get an application key from drivethrurpg and log in to torg-codex, it says I have 4 /68 products that contain Codex content. I know I have more than that—in fact I have most of the Torg sources. I don't see a way to get it to show me which ones it thinks I have, it only shows a list of missing books.

**Comment by manuel-hegner** [comment]
Can you go into your drivethru library, click on any sourcebook you own that the codex does not recognize and then post the shop link to this books store page here?

**Comment by nikgervae** [comment]
Here are a couple:

https://www.drivethrurpg.com/product/284210/Torg-Eternity--Aysle-Sourcebook
https://www.drivethrurpg.com/product/296577/Torg-Eternity--Cyberpapacy-Sourcebook
https://www.drivethrurpg.com/product/247246/Torg-Eternity--Living-Land-Sourcebook
https://www.drivethrurpg.com/product/247258/Torg-Eternity--Living-Land-Digital-Only-Set
https://www.drivethrurpg.com/product/267981/Torg-Eternity--Nile-Empire-Sourcebook
https://www.drivethrurpg.com/product/268002/Torg-Eternity--Nile-Empire-Digital-Only-Set

When I am logged in at drivethrurpg, each of those says "You Have Purchased This Title". But on torg-codex they are listed as titles I do not own.

**Comment by nikgervae** [comment]
Here are a couple:

https://www.drivethrurpg.com/product/284210/Torg-Eternity--Aysle-Sourcebook
https://www.drivethrurpg.com/product/296577/Torg-Eternity--Cyberpapacy-Sourcebook
https://www.drivethrurpg.com/product/247246/Torg-Eternity--Living-Land-Sourcebook
https://www.drivethrurpg.com/product/247258/Torg-Eternity--Living-Land-Digital-Only-Set
https://www.drivethrurpg.com/product/267981/Torg-Eternity--Nile-Empire-Sourcebook
https://www.drivethrurpg.com/product/268002/Torg-Eternity--Nile-Empire-Digital-Only-Set

When I am logged in at drivethrurpg, each of those says "You Have Purchased This Title". But on torg-codex they are listed as titles I do not own.

I have determined that torg-codex shows me content from the Core Rules and the Beta Clearance Players Primer. I don't know what the other 2 titles are that it thinks I have.

**Comment by nikgervae** [comment]
Oh hey, I had all my Torg material in my library archive. I figured I would see if moving them out into the regular library would have an effect. I did so, generated a new key, and sure enough, now torg-codex says I have 20 titles. I don't know why some of the books I had in my archive *did* show up in torg-codex, but I do have a workaround.
