### ISSUE TITLE
I am missing the Living Land books for my TORG Codex.  

### ISSUE THREAD

**Issue by SDTroll** [torg-codex/issues#64]
I am missing the Living Land books for my TORG Codex.  I have them, but not, apparently, on DriveThruRPG.   Is there some other way to show I have them?
[Torg_Eternity_-_Living_Land_Sourcebook_PREVIEW_(KS_ONLY).pdf](https://github.com/torg-codex/issues/files/12207425/Torg_Eternity_-_Living_Land_Sourcebook_PREVIEW_.KS_ONLY.pdf)
[Torg_Eternity_-_Living_Land_God_Box_PREVIEW_(KS_ONLY).pdf](https://github.com/torg-codex/issues/files/12207427/Torg_Eternity_-_Living_Land_God_Box_PREVIEW_.KS_ONLY.pdf)
[Torg_Eternity_-_Delphi_Missions_Living_Land_PREVIEW_(KS_ONLY).pdf](https://github.com/torg-codex/issues/files/12207429/Torg_Eternity_-_Delphi_Missions_Living_Land_PREVIEW_.KS_ONLY.pdf)

**Comment by manuel-hegner** [comment]
I am afraid not. We can only operate the website if we make sure every user owns the books, and we can only do this per drivethruh.

**Comment by SDTroll** [comment]
Ok, thanks for letting me know.  I guess I'll have to buy the PDFs on drivethrough
