### ISSUE TITLE
German Pan Pacifica Sourcebook doesnt get recognized

### ISSUE THREAD

**Issue by Sorebrez** [torg-codex/issues#67]
**URL:** https://www.drivethrurpg.com/de/product/478589/torg-eternity-panpacifica-quellenbuch-pdf-als-download-kaufen
**Reference Book:** Pan Pacifica
~~~
Torg Codex shows that i dont own the pan pacifica sourcebook, but i have the german version in my drivethru library. Already tried to generate a new key. As i just saw another closed issue. It is also not archived.

**Comment by manuel-hegner** [comment]
I have added the mapping, though the pan pacifica sourcebook was never fully integrated.

**Comment by Sorebrez** [comment]
Thanks for your work but it seems like this hadn't solved the issue. The Pan Pacifica sourcebook still shows as not owned on torg-codex for me. Is there any additional info i can give you?

**Comment by manuel-hegner** [comment]
Mhh. The deployment failed. I will look into it and get back to you
